version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - ruby_version: "27"
    - ruby_version: "27-x64"
  access_token:
    secure: MUwzEeu3LgJ7eEBuF1mBJHcd6uWWxvEFRpLVQbLEem7fGBEJs9c7hThRshic+M1h
  MEDIUM_USERNAME: kusumandaru
  GENERATE: true
install:
  - SET SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler
  - bundle install --retry=3
build: off
test: off