image: Visual Studio 2019
version: 1.0.{build}

skip_tags: true

environment:
  matrix:
    - ruby_version: "27"
    - ruby_version: "27-x64"
  access_token:
    secure: MUwzEeu3LgJ7eEBuF1mBJHcd6uWWxvEFRpLVQbLEem7fGBEJs9c7hThRshic+M1h
  MEDIUM_USERNAME: kusumandaru
  GENERATE: false
install:
  - SET PATH=C:\ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --conservative
  - bundle config --local path vendor/bundle
  - bundle install
build: off